### PR TITLE
[semver:patch] - Updated the cache key to use the branch name instead of a checksum

### PR DESCRIPTION
**Pull request by Fgerthoffert**
The initialize job previously contained a cache named based on a checksum of a yarn.lock file. The issue is that not all modules have a yarn.lock file.

This updates the job to use the branch name, instead of the checksum of yarn.lock (which might not be present).

Note that this is only useful for javascript modules and javascript tests. Of those are not there, nothing will be saved.

### CODE REVIEW

**Comment by rknj** [comment]
But with this, the cache will never be updated on master/main or long living branches?

**Comment by Fgerthoffert** [comment]
It will expire after 2 weeks (the regular cache lifecycle), but yes otherwise it will not be updated.

It's not necessarily a big issue, it just means during those two weeks, yarn will start from this base cache and perform the changes on top of this cache.

I was also thinking a bit about it and we might actually be able to do without cache for the tests since `yarn` is also executed during docker build (i.e. Circleci does not use Cypress directly, it runs the Docker container that uses Cypress) .

**Comment by tdraier** [comment]
Actually, it does make sense to use a "stable" key - but I would rather directly use the same cache for all branches. I don't see a reason to use different cache for each branch ?

**Review by rknj — APPROVED** [review]

**Comment by Fgerthoffert** [comment]
I reverted the change on the initialize job

**Pull request closed without merging**
